live_config_reload = true
working_directory = "None"

import = [
	"~/.config/alacritty/keybindings.toml",
]

[bell]
animation = "EaseOutExpo"
command = "None"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#1f2025"
blue = "#0090ea"
cyan = "#00f8f8"
green = "#87ff00"
magenta = "#ff1dce"
red = "#dc0000"
white = "#ececec"
yellow = "#ffda26"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#000000"
blue = "#4196f6"
cyan = "#3bc9c7"
green = "#87d700"
magenta = "#cd29d9"
red = "#c91b00"
white = "#c5c8c6"
yellow = "#ffc026"

[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellBackground"
text = "CellBackground"

[cursor]
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "Off"
shape = "Block"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "alacritty"

[font]
size = 13.0

normal = { family = "CodeNewRoman nerd font", style = "Regular" }
bold   = { family = "CodeNewRoman nerd font", style = "Bold"    }
italic = { family = "CodeNewRoman nerd font", style = "Italic"  }

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\" {-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "O"
mods = "Command"

[hints.enabled.mouse]
enabled = true
mods = "None"

[mouse]
hide_when_typing = true

# [mouse.double_click]
# threshold = 300

# [mouse.triple_click]
# threshold = 300

# [light.bright]
# black = "#666666"
# blue = "#0090ff"
# cyan = "#00ffff"
# green = "#00ff00"
# magenta = "#ff1dce"
# red = "#fc0000"
# white = "#eaeaea"
# yellow = "#ffda26"

# [light.normal]
# black = "#000000"
# blue = "#4499f7"
# cyan = "#3bc9c7"
# green = "#00c200"
# magenta = "#c930c7"
# red = "#c91b00"
# white = "#c5c8c6"
# yellow = "#ffa026"

# [light.primary]
# background = "#ffffff"
# foreground = "#050505"

[scrolling]
history = 0
multiplier = 1

[selection]
save_to_clipboard = false

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new", "-A"]

[window]
decorations = "None"
dynamic_padding = false
dynamic_title = false
opacity = 0.9
resize_increments = true
blur = true
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 140
lines = 50

[window.padding]
x = 0
y = 0

[window.position]
x = 350
y = 489
