[bell]
animation = "EaseOutExpo"
command = "None"
duration = 0

[cursor]
unfocused_hollow = false
vi_mode_style = "Block"

[cursor.style]
blinking = "Off"
shape = "Block"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "alacritty"

[font]
size = 12.0

normal = { family = "CaskaydiaCove nerd font", style = "Regular" }
bold   = { family = "CaskaydiaCove nerd font", style = "Bold"    }
italic = { family = "CaskaydiaCove nerd font", style = "Italic"  }

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\" {-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "O"
mods = "Command"

[hints.enabled.mouse]
enabled = true
mods = "None"

[mouse]
hide_when_typing = true

# [mouse.double_click]
# threshold = 300

# [mouse.triple_click]
# threshold = 300

# [light.bright]
# black = "#666666"
# blue = "#0090ff"
# cyan = "#00ffff"
# green = "#00ff00"
# magenta = "#ff1dce"
# red = "#fc0000"
# white = "#eaeaea"
# yellow = "#ffda26"

# [light.normal]
# black = "#000000"
# blue = "#4499f7"
# cyan = "#3bc9c7"
# green = "#00c200"
# magenta = "#c930c7"
# red = "#c91b00"
# white = "#c5c8c6"
# yellow = "#ffa026"

# [light.primary]
# background = "#ffffff"
# foreground = "#050505"

[scrolling]
history = 0
multiplier = 1

[selection]
save_to_clipboard = false

[terminal.shell]
program = "/opt/homebrew/bin/tmux"
args = ["new", "-A", "-s", "main"]

[window]
decorations = "None"
dynamic_padding = false
dynamic_title = false
opacity = 0.9
resize_increments = true
blur = true
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 164
lines = 55

[window.padding]
x = 0
y = 0

[window.position]
x = 350
y = 480

[general]
live_config_reload = true
working_directory = "None"

import = [
	"~/.config/alacritty/keybindings.toml",
	"~/.config/alacritty/primary.toml",
	# "~/.config/alacritty/themes/themes/catppuccin_latte.toml",
]

[terminal]
