#!/usr/bin/env bash

# Some ls aliases
# Use exa if it is available
if command -v exa &> /dev/null
then
  alias ls='exa -F'
  alias la='exa -Fa'
  alias ll='exa -FlhH --sort=extension'
  alias lt='exa -FT'
  alias tree='exa -FT'    # Tree replacement
elif [[ "$OSTYPE" == "linux"* ]]; then
  alias ls='ls -F --color=auto'
  alias la='ls -A --color=auto'
  alias ll='ls -l --color=auto'
elif [[ "$OSTYPE" == "darwin"* ]]; then
  alias ls='ls -FG'
  alias la='ls -FGA'
  alias ll='ls -FGl'
fi

# Common commands
alias mv='mv -vi'
alias cp='cp -vi'
alias ln='ln -v'
alias du='du -h'

if command -v grm &> /dev/null; then
  alias rm='grm -vI'
  alias del='gmv -t ~/.Trash'
elif [[ "$OSTYPE" == "linux"* ]]; then
  alias rm='rm -vI'
  alias del='mv -t ~/.Trash'
fi

alias mkdir='mkdir -pv'

# Grep color — Seriously though use ripgrep
alias grep='grep   --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

if command -v nvim &> /dev/null; then
  alias vim='nvim'
fi

# make commands
alias clean='make clean'
alias rebuild='bear make -B -j4'

alias path='echo -e "${PATH//:/\\n}"' # Print one directory in the path variable per line
alias vtop='vtop -t brew'
alias clock='tty-clock -C 4 -Sc'

alias C='cd ~/Code/C'
alias cs50='cd ~/Code/cs50'
