# vim: ft=ruby
brew "ag"
brew "fd"
brew "sd"
brew "gh"
brew "git"
brew "zsh"
brew "tig"
brew "bat"
brew "exa"
brew "fzf"
brew "make"
brew "tmux"
brew "bear"
brew "curl"
brew "wget"
brew "rust"
brew "dust"
brew "procs"
brew "elixir"
brew "ctags"
brew "ninja"
brew "cmake"
brew "astyle"
brew "cppman"
brew "zoxide"
brew "ripgrep"
brew "thefuck"
brew "libmagic"
brew "starship"
brew "rust-analyzer"

# tap "jgavris/rs-git-fsmonitor https://github.com/jgavris/rs-git-fsmonitor.git"
# brew "rs-git-fsmonitor"
