# vim: set ft=conf
brew "fd"
brew "sd"
brew "gh"
brew "git"
brew "bat"
brew "exa"
brew "make"
brew "tmux"
brew "bear"
brew "curl"
brew "wget"
brew "rust"
brew "dust"
brew "procs"
brew "ctags"
brew "broot"
brew "astyle"
brew "ranger"
brew "cppman"
brew "ripgrep"
brew "starship"

tap "jgavris/rs-git-fsmonitor https://github.com/jgavris/rs-git-fsmonitor.git"
brew "rs-git-fsmonitor"
