#!/usr/bin/env bash

set completion-ignore-case on
set show-all-if-ambiguous on

set keymap vi-insert
set editing-mode vi
set show-mode-in-prompt on

set vi-ins-mode-string \1\e[34;1m\2
set vi-cmd-mode-string \1\e[33;1m\2

set expand-tilde  off
set convert-meta  off
set input-meta    on
set output-meta   on
set visible-stats on

# Key binds
"jj": "\e"
"\C-x\C-e": edit-and-execute-command
"\C-p":     previous-history
"\C-n":     next-history
"\C-l":     clear-screen
TAB:        menu-complete
"\e[Z":     menu-complete-backward
