#!/usr/bin/env bash

if [[ -d "$HOME/.local/llvm" ]]; then
  llvm_install_dir="$HOME/.local/llvm"

  # export CPPFLAGS="${CPPFLAGS:+${CPPFLAGS} }-isystem $llvm_install_dir/include/c++/v1"
  export LDFLAGS="${LDFLAGS:+${LDFLAGS} }-L$llvm_install_dir/lib -Wl,-rpath,$llvm_install_dir/lib"
  export LDFLAGS="${LDFLAGS:+${LDFLAGS} } -lc++ -lc++abi -fuse-ld=lld"
  export CXXFLAGS="-stdlib=libc++ -isystem $llvm_install_dir/include/c++/v1"

  [[ ":$PATH:" != *"$llvm_install_dir/bin"* ]] && PATH="$llvm_install_dir/bin:${PATH}"

  export CC="clang"
  export CXX="clang++"
fi
