#!/usr/bin/env bash

if [[ -d "$HOME/.local/llvm" ]]; then
  llvm_install_dir="$HOME/.local/llvm"
fi

if [[ -n $llvm_install_dir ]]; then
  export CPPFLAGS="${CPPFLAGS:+${CPPFLAGS} }-I$llvm_install_dir/include/c++/v1"
  export LDFLAGS="${LDFLAGS:+${LDFLAGS} }-L$llvm_install_dir/lib -Wl,-rpath,$llvm_install_dir/lib"
  export LDFLAGS="${LDFLAGS:+${LDFLAGS} } -lc++abi"
  path+=($llvm_install_dir/bin)

  export CC="$llvm_install_dir/bin/clang"
  export CXX="$llvm_install_dir/bin/clang++"
fi

